[package]
name = "reservoir-sampling"
description = "Implementations of a variety of algorithms for reservoir sampling in Rust."
keywords = ["random", "rng", "streaming"]
repository = "https://github.com/DesmondWillowbrook/rs-reservoir-sampling"
categories = ["algorithms"]
version = "0.2.1"
authors = ["Kartavya Vashishtha <kartavya0703@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# TODO: weighted = ["binary-heap-plus"]
streaming_iterator_support = ["streaming-iterator"]

[dependencies]
rand = "0.7.*"

# compare = "0.1.0"
# TODO: binary-heap-plus = { version = "0.4.*", optional = true}
streaming-iterator = { version = "0.1.5", optional = true}